version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres-iot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
